bn222/cluster-deployment-automation

clusterConfigSchema.yml
clusterDeployer.py
clustersConfig.py

this series implements the discussed pool changes:
- patch 1 allows pool directory configuration on per host basis via yaml, and changes the default to /home/images_path
- patch 2 allows destroying the cluster pool at teatdown time
- patch 3 explicitly checks the relevant pool is not initialized before creating it
Note: this does not introduces yet others hosts-level attributes (e.g. api_network_port), as they should go via separate changeset

VM pool handling improvement

---

clusterDeployer.py
host.py

Cuncurrent VM creation can fail due to virt-installer limitation. Let's wait until the newly created VM is started before moving over to avoid failure on slow/busy hypervisors.

safer VM creation

---

clusterDeployer.py

The reason is that preconfig also may depend on the ISO path being mounted.

Mount the ISO path earlier to the start of the deployment.

---

clusterDeployer.py
clustersConfig.py

Some servers in our Lab have interface names that are different then other servers. For example "eno1" may not exist on some servers. Thus, the first interface with a carrier signal may not be the correct interface. In our GSheet we should make sure that the provisioning interface is aligned with the Provision Host column.

Automatically determine the network API port from GSheets

---

clusterDeployer.py
configCVO.py
configOperators.py
extraConfigBFB.py
extraConfigCNO.py
extraConfigDpuInfra.py
extraConfigDpuTenant.py
extraConfigOvnK.py
extraConfigSriov.py
manifests/nicmode/hardware-offload-config.yaml.j2
manifests/nicmode/sriov-node-policy.yaml.j2
manifests/tenant/SriovNetworkNodePolicy.yaml.j2
manifests/tenant/hardware-offload-config.yaml.j2

These commits introduce changes to how post config works for DPU and NIC mode clusters:
```
NIC Mode:
postconfig:
- name: "sriov_network_operator"
- name: "switch_to_nic_mode"
- name: "sriov_ovs_hwol"
Infrastructure Cluster (No Change):
postconfig:
- name: "dpu_infra"
Tenant Cluster:
postconfig:
- name: "dpu_tenant_mc"
- name: "sriov_network_operator"
- name: "dpu_tenant"
kubeconfig: "/root/kubeconfig.infracluster"
mapping:
- bf: bf-{{worker_number(0)}}
worker: worker-{{worker_number(0)}}
- bf: bf-{{worker_number(1)}}
worker: worker-{{worker_number(1)}}
```
The "sriov_network_operator" must now be an explicit configuration step. This splits the dpu tenant extra config into 2 parts: "dpu_tenant_mc" and "dpu_tenant".
You could also provide images to CNO, OVN-K, and SR-IOV network operator. …

Add Device Plugin Management Port

---

clustersConfig.py

Fixes the following error:
(ocp-venv) [root@wsfd-advnetlab228 cluster-deployment-automation]# python3.6 main.py ../nhe/cluster-deployment-automation-configs/config-nic-mode.yaml -t /usr/local/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
from cryptography.hazmat.backends import default_backend
Traceback (most recent call last):
File "main.py", line 3, in <module>
from clustersConfig import ClustersConfig
File "/root/sal_cda_deploy/cluster-deployment-automation/clustersConfig.py", line 57, in <module>
class ClustersConfig():
File …

fix TypeError

---

extraConfigDpuTenant.py
manifests/tenant/envoverrides.yaml

github.com/openshift/dpu-network-operator/pull/60 requires that the mapping in env-overrides is available to the
openshift-dpu-network-operator ns.

Copy env-overrides to dpu operator ns

---

extraConfigBFB.py
extraConfigDpuInfra.py
extraConfigSriov.py

The 'oc wait mcp ...' command occasionally returns before the MCP (MachineConfigPool) has been fully updated, leading to potential issues with reliability.
Improve reliability of 'oc wait mcp ...' command by adding debug output for verification.

Add debug info to mcp updates

---

extraConfigBFB.py
extraConfigDpuInfra.py
extraConfigDpuTenant.py
extraConfigSriov.py
k8sClient.py

On occasion an edge case can be reached where the initial wait for the sriov mcp to update is completed but a change is still pending, resulting in the nodes becoming 'unready' post script completion.
This results in failed CI runs due to the cluster being in an unexpected state.
Ensure each resource is successfully applied.

Wait for each sriov resource to be applied

---

host.py

Typically we have been able to provide Redfish the iDrac ip alone. However, a bug was introduced recently in aicli which causes insert_iso() to fail due to self.baseurl being set incorrectly.
https://github.com/karmab/aicli/pull/45
As a workaround, we can provide the full url instead.

Use full bmc url

---

clusterDeployer.py
clustersConfig.py
extraConfigRT.py
k8sClient.py
manifests/rt/sno-realtime.yaml
manifests/rt/worker-realtime.yaml

This adds logic to use a postconfig for installing a real-time kernel on worker nodes (or the single node in case of SNO). The manifest is included in `manifests` and not in-lined to give the user the ability to manually remove the machine config later on if needed (this is handy while making comparison tests).
Suggestions are welcomed as I'm not used to play with OCP. This was tested while setting up an OCP SNO in a virtual machine.
As a side note, I think documenting postconfigs would be nice. I did not include such a change here as I have no idea what the other postconfig do :)

Postconfig for installing rt kernel on workers (and SNO)

---

clusterDeployer.py

We need to restart the libvirtd after modify the config file, or it will not works. 
Move function configure_bridge() after this, which will enable and start libvirtd after the modify.
Fixes: bcc6575 ("Configure qemu user an group to be root")

Start libvirtd after modify the config file

---

clusterDeployer.py
coreosBuilder.py
host.py

This also changes the directory used for the download, and set it to the current working directory.
Before this patch:
- masters downloaded to cwd and used iso in cwd
- workers downloaded in /root/iso, and used iso in cwd
- bf downloaded in /root/iso and used iso in /root/iso Now:
- masters download to cwd and uses iso in cwd (unchanged)
- workers download in ** cwd ** if iso not present, and uses iso in cwd
- bf download in /root/iso and uses iso in /root/iso (unchanged)
This speed-up installation time

Avoid (re)downloading iso for worker VMs (x86_64) if already present

---

clusterDeployer.py
host.py

It's useful to be able to poke around in the cluster while it's coming
up.

Get kubeconfig from AI as soon as masters are installed.

---

clusterDeployer.py

Otherwise we try to start master VMs without proper qemu configuration changes (run as root) or without the bridge being configured properly.

QEMU and bridge configuration must happen before masters are started.

---

clusterDeployer.py
host.py

Pass the file name instead of temp file object for non-local hosts.

Fix remote Host.write() calls.

---

cda.py

Commit c14c3c2bf8e3 ("Add capability to snapshot clusters (VMs only for now)") accidentally broke it.

cda: Fix 'teardown-full' support.

---

clusterDeployer.py

We were incorrectly searching for the config key in the destination dictionary.  Of course, the key is not there yet, causing an exception to be thrown:
File "clusterDeployer.py", line 535, in create_cluster
if cfg["proxy"]:
KeyError: 'proxy
Fixes: 9562e6e36de3 ("Fix proxy configuration")

clusterDeployer: Check cluster config src dict instead of the dest one.

---

clusterDeployer.py
requirements.txt

If the cluster name didn't change but the API IP did, the deployer didn't update /etc/hosts.
Move the /etc/hosts update earlier in the cluster bring up to allow accessing the API externally as early as possible.

clusterDeployer: Always update /etc/hosts with the current api_ip.

---

clusterConfigSchema.yml

Commit c14c3c2bf8e3 ("Add capability to snapshot clusters (VMs only for now)") changed the attribute from 'images_path' to 'image_path' but didn't update the schema.

clusterConfigSchema: Fix image_path attribute name.

---

clusterDeployer.py

The iso is the same for all nodes.  Log the operation at INFO level to make it more visible.

clusterDeployer: Only copy the worker ISO once per bare metal node.

---

host.py

Without it we just log the Result object's address, e.g.:
2023-10-26 06:51:00 INFO: Finished starting VM dceara-worker-1, cmd =
virt-install
--connect qemu:///system
-n dceara-worker-1
-r 32784
--cpu host
--vcpus 8
--os-variant=rhel8.6
--import
--network bridge=virbr0,mac=52:54:6e:2e:94:8d
--events on_reboot=restart
--cdrom /home/dceara-cluster_guests_images/dceara-cluster-x86.iso
--disk path=/home/dceara-cluster_guests_images/dceara-worker-1.qcow2
--wait=-1
, ret = <host.Result object at 0x7f174602d4f0>

Host: Implement __str__() to get relevant error messages.

---

clustersConfig.py
dependencies.sh

Python3.11 is needed for typing (e.g.
Optional[logging.StreamHandler[TextIO]])
Fix NodeConfig class to use setattr instead of
the base class init.

Fix errors due from cleanup

---

assistedInstaller.py
clustersConfig.py
common.py

We cannot use clustersConfigs.all_nodes() before appending the NodeConfig instances to self.masters / self.workers.
Fix some incorrect syntax in ip r commands

NodeConfigs must be created before calling all_nodes()

---

clusterDeployer.py

AI doesn't return a valid API VIP until at least one cluster node is up. The safest bet right now is to wait until `wait_cluster()` returns.  At that point nodes are up.
Fixes: b1d66d3a84e7 ("clusterDeployer: Always update /etc/hosts with the current api_ip.")

clusterDeployer: Update /etc/hosts after the AI cluster is up.

---

clusterDeployer.py

Ensure NM doesn't remove the interface from virbr0 while in use and return it back to NM on teardown.

clusterDeployer: Manage/unmanage api interface in NetworkManager.

---

clusterDeployer.py
clustersConfig.py

There were two issues with the current branch:
- The code assumed the ingress_ip and api_ip configuration was always present.
- The installer added some ingress_ip and api_ip checks before removing it from the SNO configuration. This patch does not add them in the first place.
Fixes #91

Fix sno installations which do not require an API or ingress IP.

---

clusterDeployer.py
clusterInfo.py
clustersConfig.py
extraConfigDpuTenant.py

The IMPI addresses are no longer +1, as was previously the default. They can now accept jinja syntax to read a bmc_ip from the spreadsheet.
For example, you can now write `bmc_ip: "{{bmc_ip(0)}}"`
bmc_ip bug: https://issues.redhat.com/browse/NHE-934

Bmc jinja parsing

---

README.md
assistedInstaller.py
assistedInstallerService.py
clusterDeployer.py
clustersConfig.py
requirements.txt

Recently aicli stopped supporting `api_vip` and requires `api_vips` to be used instead (as a list).
Also, to avoid unexpected failures in the future, freeze the aicli version.

Fix api_vip usage.

---

clustersConfig.py

Due to the migration, the ANL Lab google sheets now contain some entries with the abbreviated hostname and some with the full hostname.
CDA can now accept both forms of hostname in the google sheet, and also provides an error message when the hostname is not found.

Check both full hostname and abbreviated hostname

---

clustersConfig.py

The old regex for extracting the worker number no longer works. For example
`wsfd-advnetlab246.anl.eng.bos2.dc.redhat.com`
Produces worker number of `2462` because of the extra 2 in bos2, instead of `246`
The new regex takes all of the digits after `lab`, or uses the old regex if there is no `lab`.

Fix error where bos2 is in worker number

---

extraConfigCX.py
extraConfigRunner.py
host.py

This will be used in a new Jenkins job to test the CX card.
- Add `cx_firmware` to `extraConfigRunner.py`
- Add file `extraConfigCX.py`
- Add `class HostWithCX(Host):` in `host.py` in the style of `HostWithBF2`
- depends on PR for cx_fwup in dpu-tools <https://github.com/bn222/dpu-tools/pull/20>

Add preconfig step to update CX firmware

---

common.py

Small change, didn't see why not to change it. Changed all references to `IPRouteAdressEntry` to `IPRouteAddressEntry`

fix typo IPRouteAdressEntry

---

README.md
clustersConfig.py
extraConfigCustomOvn.py
extraConfigOvnK.py
extraConfigRunner.py
k8sClient.py
manifests/ovn/build_ovn_ds.yaml

The advantage of the new post processing step is that it builds everything in-cluster, without the need of an external image builder or access to OpenShift registries.
Also ensure that the ovn-k extra config properly waits for the new image to be rolled out.

Add support for automatically rebuilding OVN images from upstream source and redeploying OVN-K.

---

.gitignore
extraConfigSriov.py
host.py
manifests/nicmode/sriov-operator-config.yaml

With the eventual move to
https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/doc/design/switchdev-refactoring.md
we will now need to both:
- Create SriovOperatorConfig (this is done automatically by make deploy)
- Specify SriovOperatorConfig.configurationMode.

Add sriov operator config

---

clusterDeployer.py
common.py

I was running into an issue in microshift where the port being "auto" gave the error `Failed to get ip when hosting file {file} on nfs`
I took the logic from clusterDeployer, put it in `get_auto_port` and called it from `_validate_api_port` & `port_to_ip`

Add `get_auto_port` so NFS can work with auto

---

clusterDeployer.py

This is in fact fatal. Not just an INFO.

clusterDeployer: adjust error message about CPU core check

---

clusterDeployer.py

- `update_etc_hosts` not removing hosts matching the api_vip. `hosts.add` won't insert it if the api_vips are the same
- remove extra call to `update_etc_hosts`

Add remove api_vip, remove extra update_etc_hosts

---

cda.py

Set the executable bit for "cda.py" and add a shebang. It's more convenient to use. It also makes it clear, that this is an executable.

[th/cda-executable] cda: make "cda.py" script executable

---

cda.py
clustersConfig.py

Python's logging.warn() is long deprecated for logging.warning(). See for example [1].
This causes deprecation warnings like
```
/root/cluster-deployment-automation/cda.py:22: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
logger.warn("Applying workaround for assisted installer issue")
2024-03-08 12:11:14 WARNING: Applying workaround for assisted installer issue
```
[1] https://docs.python.org/3/library/logging.html#logging.warning

[th/deprecated-logging-warn] cda: use logger.warning() instead of deprecated warn()

---

.flake8
.github/workflows/test.yml
clusterDeployer.py
clustersConfig.py
extraConfigDpuInfra.py
extraConfigDpuTenant.py

- github: print version of used linters
- flake8: enable flake8-comprehensions check
- github: run mypy check against entire directory
- github: run "mypy" check in lint job
- github: don't run lint test with Python 3.9,3.10
- github: run workflows on all branches/pull-requests
- github: run flake8 linter in github actions
- flake8: adjust exclude pattern in config file
- all: fix invalid escape sequences in strings
This also includes #124, because the flake8 check also flags the invalid escape sequences, and the branch wouldn't pass CI, without that patch. Abandon #124 and let it be handled here.

[th/flake8-check] adjust github actions and run flake8

---

README.md

It's useful to have the complete steps listed, so they can be conveniently
copy and pasted.
- include the installation of python3.11 in the installation steps.
- use `systemctl enable --now libvirtd`, because after a fresh install the
daemon is not yet running (and we probably want that).

[th/readme-install] README: update steps in documentation how to install

---

dependencies.sh

See [1]:
On August 15, 2023, the Kubernetes project announced the general
availability of the community-owned package repositories for Debian and
RPM packages available at pkgs.k8s.io. The new package repositories are
replacement for the legacy Google-hosted package repositories:
apt.kubernetes.io and yum.kubernetes.io.
See also the differences between the Google hosted repository and the new Kubernetes package repository ([3]).
In this case, select Kubernetes version v1.29 ([4])
[1] https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/
[2] https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/
[3] https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/#what-are-significant-differences-between-the-google-hosted-and-kubernetes-package-repositories …

[th/update-kubernetes-yum-repo] dependencies: use kubernetes community-owned package repositories

---

extraConfigRunner.py
extraConfigSriov.py
manifests/nicmode/sriov-namespace-config.yaml
manifests/nicmode/sriov-operator-group.yaml
manifests/nicmode/sriov-subscription.yaml

There was an issue where the CI wasn't building sr-iov to quay, which `make deploy` gets sr-iov from. This broke some sr-iov deployments.  
This commit adds the option to install sr-iov from a subscription.
- Add ExtraConfigSriovSubscription following the [ocp directions](https://docs.openshift.com/container-platform/4.15/networking/hardware_networks/installing-sriov-operator.html)
- Add `check_sriov_installed` to confirm sr iov is installed

Add sriov install from subscription instead of quay

---

clusterHost.py

The code was incorrectly building a list (generator) of image names instead of a set (which implies uniqueness).

clusterHost: Only copy images once.

---

clusterDeployer.py
clusterHost.py
clustersConfig.py
common.py
virtualBridge.py

This allows multiple concurrent CDA deployments on the same VLAN.

Add ebtables rules to drop unexpected DHCP replies.

---

clusterHost.py

Commit ae68be3d9cdb ("clusterHost: Only copy images once.") tried (and failed) to do that.  That's because the node.config.image_path attribute already includes the node name.  What it should've done was to build the set of unique target directories.  Do that instead.

clusterHost: Really only copy VM images once per host.

---

coreosBuilder.py

The previous podman command does not seem correct. It follows the documentation [1], but note that the doc says:
>  Note: You should run this command as non-root
>  It's also fully supported to use podman as root, but some of the
>  arguments here need to change for that.
But then, the command line was as if we were to run the container rootless. Note that /tmp/build/fcos is owned by root, as it is created by CDA.
Consequently, there is a failure:
```
rm: cannot remove '/dev/kvm': Device or resource busy
failed to execute cmd-fetch: exit status 1
```
It seems to be because /dev/kvm is bind mounted inside the container. As such, it cannot be removed and [2] fatally fails.
It's unclear how the previous command was ever working. It must work in some cases, but it doesn't work for me. Note …

[th/coreos-build-rootful] coreosBuilder: fix rootful coreos build via podman

---

assistedInstaller.py
clusterDeployer.py
clusterHost.py

When provisioning large numbers of workers at a time this can take long. Logging helps.
The second commit unifies the style of most of the remaining infinite loops trying to avoid boilerplate code.

Log while waiting for workers to be ready.

---

dependencies.sh

Don't silently ignore errors in dependencies script.
---
This patch is from #131. It is not OK to ignore errors, it hides real problems. For example, when b75101b55353e06a317818d7defe26dbc41094e0 was necessary, the script encountered an error but did not make it obvious. It takes time to notice that the dependencies were not properly installed.

[th/dependencies-fail-on-error] dependencies: abort script on error

---

arguments.py
assistedInstaller.py
assistedInstallerService.py
clusterDeployer.py
clusterHost.py
clusterInfo.py
clusterNode.py
clusterSnapshotter.py
clustersConfig.py
common.py
extraConfigBFB.py
extraConfigCNO.py
extraConfigCX.py
extraConfigCustomOvn.py
extraConfigDpuInfra.py
extraConfigDpuTenant.py
extraConfigDualStack.py
extraConfigOvnK.py
extraConfigRT.py
extraConfigRunner.py
extraConfigSriov.py
host.py
k8sClient.py
virtualBridge.py

Since Python 3.9, the standard collections support being used as generic types.
CDA depends on Python 3.10.
See https://docs.python.org/3/library/typing.html#typing.List:
> Deprecated since version 3.9: builtins.list now supports subscripting ([]). See [PEP 585](https://peps.python.org/pep-0585/) and [Generic Alias Type](https://docs.python.org/3/library/stdtypes.html#types-genericalias).

[th/typing-standard-collections] use standard collections (like `list`) instead of `typing.List`

---

assistedInstaller.py
clusterDeployer.py
clusterHost.py
coreosBuilder.py
dependencies.sh
virtualBridge.py

With this we can now deploy fully virtualized clusters on a single physical node (workers and masters running in VMs on the same host).

Require a physical port (network_api_port) only if needed.

---

logger.py

Logging is mostly useful for debugging and understanding what happens. Support setting the log level via "$CDA_LOG_LEVEL" environment variable. This allows to enable logging for example for unit tests or ad-hoc test commands:
```
$ CDA_LOG_LEVEL=debug pytest -v -s
$ CDA_LOG_LEVEL=debug python -c 'import host; h = host.LocalHost(); print(h.run("ls -l").out, end="")'
```

[th/log-level] logger: make log level configurable via CDA_LOG_LEVEL environment variable

---

assistedInstaller.py
clusterDeployer.py
clusterSnapshotter.py
common.py

The kubeadmin secret is useful. With it we can `oc login` and get a token with `oc whoami -t`. I think from the X.509 certificate we cannot get a comparable token.
Note that there is a change in behavior here. AssistedInstaller's download_kubeconfig() does not allow to fully specify the file name. It only allows to specify the path, and the file name is always f"{path}/kubeconfig.{name}".  This means, previously the file name of self._cc.kubeconfig was not honored. Now, if the file name differs, we rename the file so that it matches what was requested.
On the other hand, the resulting kubeadmin password is always in the file f"{path}/kubeadmin-password.{name}". The user cannot affect that via configuration.

[th/kubeadmin-password] assistedInstaller: download kubeadmin-password together with kubeconfig

---

clusterDeployer.py
clusterHost.py
virshPool.py

Commit c14c3c2bf8e3 ('Add capability to snapshot clusters (VMs only for
now)') dropped the pool handling, maybe because virt-install's "--disk"
argument changed from "pool=" to "path=".
However, even with "--disk path=", libvirt will still create a pool.
As installation progresses in parallel, two virt-install instances may
decide that they need to create the pool. This can result to a failure:
```
2024-04-08 05:16:54 INFO: Finished starting VM nicmodecluster-master-3, cmd =
virt-install
--connect qemu:///system
-n nicmodecluster-master-3
-r 32768
--cpu host
--vcpus 8
--os-variant=rhel8.6
--import
--network network=default,mac=52:54:cf:41:cb:f6
--events on_reboot=restart
--cdrom /home/nicmodecluster_guests_images/nicmodecluster-x86_64.iso
--disk …
```

[th/ensure-virsh-pool] ensure libvirt storage pool exists to avoid failure of virt-install

---

extraConfigImageRegistry.py
extraConfigRunner.py

This is useful when running OpenShift builds, for example.

Add extra config to enable the image registry.

---

assistedInstallerService.py

It's not clear what the return type really is. We just parse a JSON we receive without validating the content.
Maybe some validation should be done.
Regardless, the closest type of what we return here is a strdict. Annotate the return type.

[th/ai-find-pod-return] assistedInstallerService: annotate return type of find_pod()

---

arguments.py
clustersConfig.py

Partially revert 54b9fb9df004 ("clustersConfig: Set default IP subnet to 192.168.0.0/16.").  The part that ensures that the virbr configuration is valid is OK to keep.

clustersConfig: Change default IP range to 192.168.122.1-192.168.122.254.

---

assistedInstallerService.py
cda.py

Previously, we would false match on r'4\.12\.[0-9]+' when trying to deploy 4.12.0-nightly, resulting in a bad pullspec. First try to match on the more specific nightly / ec regex.
Add consistency in version checking scheme and remove unnecessary workaround for 4.14 installation.

Fix nightly pullspecs

---

virtualBridge.py

There's no guarantee that "virsh net-define <file>" doesn't replace
double quotes with single quotes.  For example, on RHEL 9.3:
$ virsh --version
9.5.0
$  cat /tmp/vir_bridge.xml | grep resolv-file
<dnsmasq:options><dnsmasq:option value="resolv-file=/etc/resolv.conf.cda-orig" /></dnsmasq:options>
$ virsh net-define /tmp/vir_bridge.xml
Network default defined from /tmp/vir_bridge.xml
$ virsh net-dumpxml default | grep resolv-file
<dnsmasq:option value='resolv-file=/etc/resolv.conf.cda-orig'/>
The second commit in this PR logs the reasons why the bridge had to be reconfigured.

Fix and log the bridge reconfiguration events.

---

clusterDeployer.py

Avoid using cryptic q[-1][0](1:] which is sensitive to bridge configuration changes. Following commit changed the bridge configuration and hence q[-1] stopped pointing to ip.
Fixes: 03f05ec595ee ('dns: ensure libvirt's dnsmasq does not forward to the local dnsmasq')

Fix removing DHCP entries.

---

clusterDeployer.py
monitoring-config.yaml

Prometheus uses lots of disk space, until all space is used, which causes master nodes to start to fail and cluster to become unresponsive.

avoid Prometheus killing cluster

---

dnsutil.py
test_dnsutil.py
virtualBridge.py

Since commit [1], libvirt's dnsmasq used "--resolvconf" option to
"/etc/resolv.conf.cda-orig". The purpose was to avoid a DNS loop. That
happened because "/etc/resolv.conf" contains "nameserver 127.0.0.1", and
the local dnsmasq.service will forward "{cluster}.redhat.com" names to
the API host (see "/etc/dnsmasq.d/cda-cluster-{cluster_name}.conf"
file). The API host inside libvirt then can forward those requests back
to libvirt's dnsmasq. Which forwards to the local dnsmasq.service. And
so on. The result are messages like
Maximum number of concurrent DNS queries reached (max: 150)
The  problem was that we must not forward all of "{cluster}.redhat.com"
to the cluster's DNS server. We only should forward "apps", "api" and
"api-int" names. The proper solution is a more fine grained selection …

[th/dnsmasq-servers-file] dns: fix dnsmasq "server" option to only lookup apps.cluster.redhat.com

---

arguments.py
cda.py
clusterDeployer.py
clusterHost.py
clustersConfig.py
k8sClient.py
virtualBridge.py

Add ability to tear down only workers.
4 patches:
- create remove_dhcp_entries for masters and workers. This removes dhcp entries per host.
- Fix dhcp leases cleaning. Some race conditions were sometimes causing cleaning issues. Note that --wait in virsh does not work.
- Add support for teardown workers only.
- Support non consecutive static ip for nodes. So that we can configure ip as e.g. a.b.c.5, ab.c..7 ... and proper range will be calculated.

Teardown vms

---

assistedInstallerService.py
clusterDeployer.py
clusterHost.py
clusterNode.py
clustersConfig.py
common.py
extraConfigDpuTenant.py
host.py
test_common.py

- unify fetching links/addresses/routes via new/renamed API `common.ip_{links,addrs,routes}()`. Duplicated implementations are replaced.
- we fetch links/addresses/routes with a remote `ip -j link|addr|route show` call. The only sensible thing to do with that result is parsing it. That parsing should all use the same code. That code is now `common.ip_{links,addrs,routes}_parse()`. Note that most callers however are not even interested in that (because they always want the parsed output). Instead, `common.ip_{links,addrs,routes}()` gives already the parsed output and does not bother the caller with calling `ip -j link|addr|route show` separately.
- a remote call can easily fail. For example, while the worker machine is rebooting. Previously, that lead to an exception (which was mostly …

[th/ipa-validate] ignore invalid JSON input to `ipa_to_entries()`

---

clustersConfig.py
common.py
extraConfigSriov.py
host.py
reglocal.py

add option `sriov_network_operator_local` for building containers of `sriov-network-operator`.
This is a re-spin of https://github.com/bn222/cluster-deployment-automation/pull/168, but without the API changes that that branch required.

[th/sriov-local-build-2] build sriov-network-operator from master

---

host.py

```
./host.py:12:1: F401 'typing.Any' imported but unused
```

[th/host-unused-import] host: fix flake8 warning about unused import

---

clusterDeployer.py
extraConfigMicroshift.py
extraConfigRunner.py
host.py

Add a post config step which will start the microshift service.
Example config:
clusters:
- name : "iso_cluster"
api_vip: "192.168.122.99"
ingress_vip: "192.168.122.101"
network_api_port: "eno12409"
kind: "iso"
install_iso: "http://my-server/rhel9_4.iso"
masters:
- name: "216-acc"
node: "localhost"
type: "physical"
bmc: "my_imc_address.redhat.com"
bmc_user: "root"
bmc_password: "bmc_pass"
ip: "192.168.3.16"
mac: "00:09:00:01:03:18"
postconfig:
- name: "microshift"

Add post config step to start microshift on ACC

---

clustersConfig.py

This patch was introduced by PR107 (together with other patches), but PR 107 was reverted to remove the other commits from the patch (e.g. Ensure bridge is correctly configured before adding dhcp static names).
However, this network_api_port related commit fixes a real issue.
Nodes are sometimes installed with different version of OSes resulting in different naming for the interfaces for some hosts. This is usually configured by setting a default network_api_port for the cluster and overwriting it for the specified hosts. Without the patch script fails as trying to pass
network_api_port parameter twice to __init__.
Backtrace:
File "./cluster-deployment-automation/cda.py", line 88, in <module>
main()
File "./cluster-deployment-automation/cda.py", line 82, in main
main_deploy(args)
File …

Fix using different network_api_port per host.

---

clustersConfig.py
extraConfigMastersSchedulable.py
extraConfigRunner.py

Add extra post config step that allows to specify whether workloads could be scheduled on master.

Add extra post step to enable/disable scheduling on master

---

common.py
extraConfigSriov.py

`make deploy` of sriov-network-operator would install 8 images that were previously hosted on quay.io.
With "sriov_network_operator_local: True" we would rebuild 3 of them, and push them to a local registry. But the other 5 are still coming from quay.io.
Recently, those repositories from quay.io were removed. `make deploy` no longer works.
Add a script "contrib/scripts/build-images.sh" for building those images and push them to a registry. Also, images were build and pushed to quay.io/thaller.
Use those images by default.
The user can still overwrite each image by setting the respective environment variable.
Examples:
A.1) build upstream and push to quay.io:
```
$ ./contrib/scripts/build-images.sh "" "" "quay.io/$USER"
```
B.1) run local container registry:
```
$ CDA_LOG_LEVEL=debug \ …
```

[th/build-images] use separate images for sriov-network-operator

---

manifests/dpu/dpu_nad.yaml

Resource name changed to "openshift.io/dpu"
From this commit: https://github.com/openshift/dpu-operator/pull/85

Changes to DPU-Operator requires new resource name

---

extraConfigDpu.py

After installing the required version of go for building the dpu operator, the PATH for the current process will not be updated.
We could either manually hand the updated environment to every future call to run, however this is messy and puts a burden on the caller.
A cleaner solution might be to just error out and instruct the user to re-start the process with the proper PATH

Print proper error message when updating go version

---

manifests/ovn/build_ovn_ds.yaml

Add dnf config option to use the fatest mirror and bail early if some of the mirrors is super slow (<25kbp).

ovn: Make sure we are using the fatest mirror

---

common.py
extraConfigSriov.py
k8sClient.py

extraConfigSriov.py:
- Fixed CI issue by waiting for all pods in the SNO to be ready rather than wait for the crd since it is not provided by default after version 4.16.0.
- Made the change backwards compatible by keeping "wait_for_crd" if the version is older than 4.16.0.
common.py:
- Added a helper function to parse version numbers into tuple to be used to compare version numbers.
- Added a function to calculate the elapsed time.
K8client.py:
- Added a function that waits for all pods of a namespace to be ready, it retries
until ready up to 10 times.
- Added elapsed time of waiting for all pods to the above function.
All changes tested with the CI, which deployed successfully.

Fix CI issue for SNO Config Daemon on version >= "4.16.0"

---

README.md
assistedInstallerService.py
clusterDeployer.py
libvirt.py
virtualBridge.py

The Libvirt monolithic apporach was replaced in favor of modular approach. Use the modular services instead of the monolithic. At the same time make sure that the monolithic is not running at the same time with modular services.

libvirt: Use Libvirt modular instead of monolithic

---

clusterInfo.py

```
$ mypy --strict --config-file mypy.ini .
clusterInfo.py:29: error: Module "gspread" does not explicitly export attribute "authorize"  [attr-defined]
clusterInfo.py:31: error: Incompatible types in assignment (expression has type "Worksheet", variable has type "Spreadsheet")  [assignment]
clusterInfo.py:32: error: "Spreadsheet" has no attribute "get_all_records"  [attr-defined]
Found 3 errors in 1 file (checked 45 source files)
```

[th/fix-typing-gspread] clusterInfo: fix typing errors for gspread module

---

clusterDeployer.py
clusterNode.py
common.py

`IsoDeployer` subclasses `ClusterDeployer` but it shortcuts most of the functionality from the base class (including `ClusterDeployer.__init__()`). This makes it harder to understand which part of (the non-trivial) `ClusterDeployer` is actually in use.
Instead, add a `BaseDeployer` base class for both, and move the common code there.

[th/base-deployer] add a BaseDeployer class for common functionality of ClusterDeployer+IsoDeployer

---

clusterDeployer.py
extraConfigMonitoring.py
extraConfigRunner.py

The monitorign config was applied every time after post stage. Remove the implicit config as would overwrite any config that was already on the cluster.

Move cluster monitoring config into separate post step

---

clusterDeployer.py

The common method didn't work for workers because the DHCP setup is sligthly different. Revert the move into common method and just simply add the link configuration for the masters.

clusterDeployer: Fix wrong worker deployment

---

host.py

We probably need to strip the trailing newline from the line, otherwise the logging lines break lines. Use str.rstrip() for that.
However, preserve the leading spaces. They align the command output and stripping them makes the log harder to read.

[th/host-run-logging] host: don't strip leading spaces for logging command results

---

clusterInfo.py
clustersConfig.py

Since ISO installation could be pointing to internal servers, it is best that we have that information guarded in database.
Also add org id and activation key to spreadsheet as well. Earlier these were provided via jenkins credentials. Since they must be store in a special place we should add it to the database so they cannot be accessed easily.

Add ability to read ISO installation details from spreadsheet

---

.gitignore

- ctags is useful (at least to me, or anybody who likes to use this tool). It leaves a `tags` file behind, that I'd like not to see in `git status`. Ignore `/tags` file.
- allow for various venv directories, not only `ocp-venv/`. Instead, ignore `/*venv*/`. This allows to create different venvs for different python versions. Also, on other python projects, I tend to call the venv directory `./venv` (because they are not strictly ocp related). I'd like to use the same directory everywhere and don't see it in `git status`, as that is what I am used to.
In general, ignoring files that are not relevant for one or the other user (or even the majority of users), tends to be a non-issue. It would only be an issue if tomorrow a user wants to add a file `"/tags"` or `"/*venv*/"`. But even then, …

[th/gitignore] ignore ctags' `tags` file and various spellings for the `*venv*/` directory

---

kickstart.ks.j2

Generate a id_ed25519 SSH key (without password) on our worker nodes. That doesn't seem harmful to have there. Despite being password-less, unless somebody intentionally uses the public key somewhere, it does nothing.
However, there is a concrete use. The marvell-tools container can deploy RHEL on a Marvell DPU on the (worker) node. That container runs on the worker node and it (configurably) adds the host's public key "/host/root/.ssh/id_ed25519.pub" into the DPU's authorized_keys. The benefit is that subsequently, you can from the worker node just ssh into root@172.131.100.100 (if you configure the 172.131.100.1 address on eno4 interface or use the IP address from the DPU's secondary interface). Otherwise, the DPU is also not secure, because the root login is well known and a root user …

[th/kickstart-ssh-keygen] kickstart: generate an id_ed25519 on the worker node

---

virtualBridge.py

This happens during tear-down. It should not be considered fatal.
```
2024-08-26 03:49:55 DEBUG [th:140695601846080] (host.py:344): running command virsh net-update default delete ip-dhcp-range "<range start='192.168.122.2' end='192.168.122.254' />" --live --config on localhost
2024-08-26 03:49:55 DEBUG [th:140695601846080] (host.py:350): (returncode: 1, error: error: Failed to update network default
error: Requested operation is not valid: couldn't locate a matching dhcp range entry in network 'default'
)
2024-08-26 03:49:55 ERROR [th:140695601846080] (host.py:403): virsh net-update default delete ip-dhcp-range "<range start='192.168.122.2' end='192.168.122.254' />" --live --config failed: error: Failed to update network default
error: Requested operation is not valid: couldn't locate a …
```

[th/virtual-bridge-teardown] virtualBridge: don't die removing DHCP range via virsh

---

kickstart.ks.j2

Sorry for providing such a broken commit. Obviously insufficiently tested.
For one, we probably would need a `mkdir -p /root/.ssh`. But much worse, this kickstart.ks is only used by microshift.py, and not for our CoreOS workers. Which is obvious, we would probably need to place the SSH key there via ignition.
That seems more complicated than one line in shell, so I don't do that now.
This reverts commit abcb86d94c883cd29e6ee1acb8c8cc8ba7eebd19.

Revert "kickstart: generate an id_ed25519 on the worker node"

---

dpuVendor.py
extraConfigDpu.py
isoCluster.py

**STATUS: this is currently blocked** waiting for https://github.com/wizhaoredhat/marvell-octeon-10-tools/pull/7 . In the meantime, you can `export CDA_MARVELL_TOOLS_IMAGE=quay.io/thaller/marvell-tools:latest`.
---
For installing RHEL on the Marvell DPU we need to use PXE boot.  Also,
we will need to access the DPU's serial console at /dev/ttyUSB0 and
/dev/ttyUSB1 on the node.
Since we already must have code running on the worker node, also expect
that the management network port of the DPU is plugged back to the host
on interface "eno4" (configurable in marvell-tools' "--dev" option).
The secondary port of the DPU expected to be connected to the
provisioning host that runs CDA. This is usually "eno2", but
configurable via "network_api_port" in cluster YAML.
To install the DPU, CDA thus …

[th/marvell-dpu] support "kind=iso" cluster for installing RHEL on Marvell DPU

---

arguments.py
clustersConfig.py
common.py
isoCluster.py
test_common.py

- `RangeList._range` was previously a class variable. That's wrong, it
should be per instance.
- make `RangeList` immutable and drop the `include()`/`exclude()` methods.
Pass all parameters at construct time.
- no longer have this odd split between `RangeList.initial_values` and
`RangeList._range`. Instead, there is a set of includes and a set of
excludes.
- accept ranges as strings as parameters for include/exclude arguments.
- add `RangeList.UNLIMITED` singleton. It's the default for the
`ClustersConfig()` constructor.
- handle multiple `'-w"`/`"-sw" options on the command line.

[th/rangelist-cleanup] common: fixes for RangeList and make it immutable

---

.github/workflows/test.yml

he packages from requirements.txt may or may not be necessary for
running out tests. However:
- tomorrow we add a test that requires a package from
"requirements.txt", then we constantly need to keep the second
list of installed packages.
- for the test, even if they currently don't test all packages
from "requirements.txt", we want at least see that those are
installable. Install them.

[th/github-pip-requirements] github: install pip packages from "requirements.txt" in test

---

k8sClient.py

Fix typo. Also break the curl into separate commands. The current way it is written will fail when run on localhost due to the way that subprocess handles the pipe.

k8sclient: fix typo in ensure_oc_installed

---

clusterInfo.py
clustersConfig.py

Rather than detecting the full path to the iso, only detect the base url. The iso file itself will be provided by the user of CDA instead.
Update naming accordingly

clustersConfig: update autodetect for base url

---

cda.py
clustersConfig.py

"secrets_path" was a mandatory positional argument. "main_snapshot()" missed to pass that argument on. Fix that.
While at it, make the parameter a kw_only argument so that such an error not possible. Also, add a default value, since main_snapshot() doesn't have a value to set.
Fixes: ad13ce19afd2 ('Propagate secret settings')

[th/fix-secrets-path] cda: fix passing secrets_path to ClustersConfig

---

isoCluster.py

Currently, we need to cold boot the IPU host anytime the IMC reboots to ensure the netdevs are available.
Ensure the netdevs are available when isocluster deployment completes.

isoCluster: Ensure IPU netdevs on host are up

---

host.py

`K8sClient.__init__()` has a default argument with
```
host: host.Host = host.LocalHost()
```
That means, importing "k8sClient.py" will instantiate a Host instance. Note that this can easily happen. For example, while parsing the YAML in "clustersConfig.py" we may import some other modules (for example, to validate the `ExtraConfigArgs`). Those modules in turn can include `k8sClient` module.
Merely importing the module already spams the log. That seems wrong. Even if this is "only" at debug level, the debug level is enabled by default, unless you set another level (which "cda.py" does, but each tool would have to do that, and it would have to do so before importing `k8sClient` module).
Maybe default values should be trivial, and we should have `host:Optional[host.Host]=None`. But rather, …

[th/host-no-log] host: don't log message from Host() constructor

---

clusterDeployer.py
microshift.py

Also, switch to use keyword arguments (and force using kw args on microshift.deploy()) to avoid such errors in the future.
Fixes: ad13ce19afd2 ('Propagate secret settings')

[th/fix-microshift-deploy] clusterDeployer: fix passing secret_path to microshift.deploy()

---

extraConfigDpu.py

The repo_dir is configurable in the cluster YAML configuration, see "ExtraConfigArgs.dpu_operator_path". Using the hard coded default value REPO_DIR is not right, instead require the caller to pass it in.
Note that there are no callers of update_dockerfiles_with_ose_images(), so maybe this function should be just deleted. For now, that is not done, because maybe there was a plan for this function.

[th/dpu-use-repodir] extraConfigDpu: fix using repo_dir argument in update_dockerfiles_with_ose_images()

---

clusterDeployer.py

Tiny change to make ClusterDeployer a tiny bit easier (by having less state in the object, even if it is not mutated).

[th/deployer-bf-iso-path] clusterDeployer: factor out constant string "_bf_iso_path"

---

dpuVendor.py
extraConfigDpu.py

With the changes in https://github.com/openshift/dpu-operator/pull/128
we not longer need to start the vsp, this will be handled by the dpu
operator.
We will not remove the "Start" functionality, since the option to deploy
the vsp manually outside the dpu operator is maintained / will be
required for non-Intel vsps.
Update the vsp naming so that it can be properly deployed by
https://github.com/openshift/dpu-operator/pull/128.
TODO: We should add multiarch support via buildah to ipu plugins so that
we can pull a single manifest rather than needing to build and tag
multiple images individually.

Update vsp naming

---

clusterHost.py
clusterNode.py

With `__slots__`, mypy knows the valid fields of an object.
The classes are confusing enough, it's useful to see exactly which fields exist and tighten up the checks. This helps by letting the linter confirm that only those attributes exists.
Also, drop the unnecessary `VmClusterNode.ip()` function.

[th/cluster-node-strict-types] use __slots__ in ClusterNode,ClusterHost for more typing help

---

clustersConfig.py
common.py
extraConfigDpu.py

- common: don't have default "repo_dir" in common.git_repo_setup()
- common: change default "branch" for common.git_repo_setup()

[th/git-repo-setup] don't use "/root/dpu-operator" as default path and don't set a default branch (instead, honor HEAD)

---

dpuVendor.py
extraConfigDpu.py

dpuVendor: Build a multiarch ipu manifest
The dpu-operator by default expects a multiarch vsp image.
In the past, this code just worked, because we would build and push the
image immediately before deploying the operator on the respective
architecture, so the most recent image would be the proper arch.
This is flimsy, and can cause errors later on if we need to pull the
image again. Instead, as a workaround while waiting for multiarch IPU
vsp build support, build a manifest of the images during the second
phase of deployment (iso-cluster dpu).
This code makes a (potentially bad) assumption that the host side
deployment has already run, and built/pushed the x86_64 vsp.
depended on by: [1] https://github.com/openshift/dpu-operator/pull/168

Buildah manifest

---

extraConfigBFB.py

When cold booting BF-2 host to apply nic mode config, we need to make sure the systemd file to switch is first in place.

extraConfigBfb: fix race condition before coldboot

---

host.py

There is an edge case we can hit when reading from a subprocess that will cause the read operation to hang indefinitely, which is exposed by https://github.com/openshift/dpu-operator/pull/181/commits/c517b55f71b0dce4d2234dc5e64216305ee20c1d.
We can reach a deadlock when reading from both of these buffers independently with a significant amount of output coming through.
It makes more sense anyways to just read from proc.communicate() than manually reading from stdout and stderr.

host.py: fix subprocess bug

---

common.py

Avoid:
```
common.py:75: error: Argument 2 to "check_type" has incompatible type "type[Any] | str | Any"; expected "type[Any]"  [arg-type]
```

[th/typing-fix-check-type] common: fix typing error in common.check_type()

---

extraConfigMicroshift.py

```
extraConfigMicroshift.py:45: error: Returning Any from function declared to return "str"  [no-any-return]
```

[th/typing-yaml-dump] typing: fix typing annotation for yaml.dump() in extract_microshift_kubeconfig()

---

clustersConfig.py
dpuVendor.py
extraConfigDpu.py
ipu.py

dpuVendor: Specify Intel vsp commit to build from:
Since we do not yet have the Intel VSP tracked in the dpu operator, we
should add this field to the config file.
This way, changes to the vsp must be passed in the dpu operator CI
before we bump our tests to pull these in
extraConfigDpu: remove idpf netdev restart:
In theory we should no longer need to manually cold boot the servers to
ensure idpf netdevs are available.
Currently there is a bug in MeV 1.8 that causes the host to reboot any
time the IMC reboots, which masks this issue from occurring.
If this masking is removed, we want to see failure here to signify that
lifecycle management of the IPU is broken

Proper vsp testing

---

assistedInstaller.py

We can't override list_clusters() to return an unexpected data type, because other functions in the base class rely on this.
This causes an infinite loop when trying to call delete_cluster()
Rename function to be more specific

AssistedInstaller: Fix infinite loop

---

dnsutil.py

Without it, after reboot dnsmasq.service might not be running.
Also, do that always, not only when some files change or the service needs restarting.

[th/dnsmasq-service-enable] dnsutil: ensure dnsmasq service is enabled

---

.github/workflows/test.yml
mypy.ini
pyproject.toml

- move "mypy.ini" to "pyproject.toml". That is an alternative, valid location for mypy configuration. This way we have fewer files around.
- set `strict = true` and `files = "."`. The benefit is that this is how we want to run mypy. By setting these options in the configuration file, we no longer need to specify them on the `mypy` command line.

[th/mypy-config] mypy: set "strict" and "files" and move config to "pyproject.toml"

---

ipu.py

Sometimes after the first boot, things just don't work.
If we don't run the connectivity script constantly, we run the risk of not running it in the window we need to.
If we do run the connectivity script constantly, we seem to be able to break the node policy rules, such that there is no connectivity on any port no matter what we do.
Instead, add a more moderate script to run ipu_port1_setup.sh, and just reboot the IMC if things have taken too long. After the first reboot, behavior of the ACC seems much more predictable

Add workaround for flaky acc first boot

---

extraConfigDpu.py

Since the default values for the images are already something, it should still be possible to set the {builder,base}_image keys to an empty string, to use the original images from the container file.

[th/dpu-original-build-image] extraConfigDpu: in update_dpu_operator_dockerfiles() allow use original images

---

libvirt.py

Do not relay on enabled as indication for sockets to be enabled and started. Properly check for every socket and enable/active based on the status returned from systemd.

libvirt: Properly start all sockets for modular services

---

assistedInstaller.py
clusterDeployer.py
clusterHost.py
clusterNode.py
common.py
ipu.py
isoDeployer.py

Sometimes the installation fails for various reasons in AI, most common was that the registry is not accessible and the agent won't be able to download it. Add retry mechanism to the installation of workers which greatly helps with that. This code has been running in our lab for more than a week without any issue.

Installation retry

---

isoCluster.py

The current rhel-9 kernel lacks patches for the Marvell DPU (on the DPU side). This will be fixed eventually, but for now, we must install another kernel.
Marvell-tools has a command line argument to install RPMs of a suitable kernel.  Use it.
Note that the option is just called "--default-extra-packages". In the future, when the workaround is no longer necessary, then "marvell-tools" will decided that it no longer needs to install any extra packages.  In CDA, the option will always be passed to the pxeboot command.
If CDA always passes this option to pxeboot command, why does it even exist? Because the pxeboot command can be used without CDA, and because in that use case it's deemed better to not install the packages without being asked to.

[th/marvell-tools-install-kernel] isoCluster: pass "--default-extra-packages" to marvell-tools' "pxeboot.py"

---

clustersConfig.py
extraConfigMev.py
extraConfigRunner.py
host.py

Provide a pre-config to put the MeV firmware into a good state.
Reflashing the firmware takes a very long time. By default, it will not do this if the firmware is already on the desired version.
However, if we specify to force, we will reflash regardless of the current state.

Add preconfig step ExtraConfigMevFwUp

---

ipu.py

@SalDaniele , Referred to this older commit->
https://github.com/bn222/cluster-deployment-automation/commit/3e6aa4a848604f3391eb2f4ab681fab6bce8e645 
for this change, to remove WA in RHEL install case.
Need to verify with redhat

To remove WA for Intel PR 330

---

clusterInfo.py
clustersConfig.py

We have cluster-info in the [ANL lab list](https://docs.google.com/spreadsheets/d/1lXvcodJ8dmc_hcp0hzbPDU8t6-hCnAlEWFRdM2r_n0Q/edit?gid=0#gid=0). There is `clusterInfo` module to fetch that data from CDA.
That is currently used whenever we have a cluster config with Jinja2 template values. Those values come from the cluster info spread sheet.
Note that dpu-operator's `make e2e-test` can only run on certain clusters/hosts that are suitable for the test to run. dpu-operator currently does not directly detect the cluster/host, however, it's [`hack/cluster-configs`](https://github.com/openshift/dpu-operator/tree/3b8c5dc3bb11393be82bcbe92ca25c4ba9b5bc74/hack/cluster-configs) contains Jinja2 fields. So when dpu-operator runs CDA-deploy, the latter will detect the current hostname (`hostname …

[th/cluster-info-tool] make `clusterInfo.py` executable tool to fetch cluster info

---

isoCluster.py
isoDeployer.py

- implement the dection of marvell hosts (checking lspci, which is similar to what dpu-operator does).
- using NodeConfig.node is not right. We want to use NodeConfig.bmc to reach the host.

[th/marvell-dpu-fixes] marvell: fix isoCluster for marvell DPU

---

assistedInstaller.py
clusterDeployer.py

The master cannot be easily retried as workers, fail the whole installation if one of the masters fail to install. This is needed instead of the callback trick. The callback trick will fail, however the futures will keep running and there isn't any way to stop them so the whole installation gets stuck anyway.

deployment: Fail installation when one of the masters fail

---

isoCluster.py
isoDeployer.py

_pxeboot_marvell_dpu() already hard coded the user name "core" for ssh-ing into the DPU's host.
We also need to do that earlier, during is_marvell(), because we assume that bmc.user is not actually correct. See commit 4e24fedc931e ('marvell: hard code the BMC user name "core"') why that is done.
While at it, move is_marvell() to isoCluster.py, beside the other marvell related functions.

[th/is-marvell-fix] marvell: move is_marvell() detection and use correct ssh user

---

clusterInfo.py
clustersConfig.py

The spreadsheet can now have a value "secondary" in the "Provision host"
column. I already updated the spreadsheet already to contain this entry.
In that case, the "Ports" column contains the "ClusterInfo.secondary_network_port".
This is also accessible in Jinja2 like
network_api_port: {{ secondary_network_port() }}
We need this for the Marvell DPU clusters.
Note that with cluster-kind "iso" deployments, the
"secondary_network_port" of the cluster configuration has a different
(but useful) meaning than from "openshift" kinds. On all IPU clusters,
this value is currently "eno12409". On all Marvell DPU clusters, it is
currently "eno2".
As we want that a single cluster configuration works for our IPU and
Marvell DPU clusters, and as this port differs between clusters, we must
make it …

[th/cluster-info-iso-port] clusterInfo: add "iso_network_api_port"

---

extraConfigDpu.py

There is an issue that causes go multiarch to hang indefinitely sometimes: https://github.com/golang/go/issues/70329
Per the comments on the issue, it seems setting GOMACPROCS to a small number can relieve this issue as a temporary WA

Add workaround to prevent go build from hanging

---

assistedInstallerService.py

As of 2/25/2025 the iso name in the openshift dev repo [1] no longer matches what is expected by assisted installer service [2].
While we try to remedy this with the respective teams, this workaround will ensure deployments work in the meantime.
[1] https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/dev-4.19/
[2] https://github.com/openshift/assisted-service/blob/master/deploy/podman/configmap.yml#L25

Add workaround for 4.19 coreos images

---

clusterDeployer.py

This wait time seems too short for some setups. We give up too early, and retry installing (booting) the worker node from scratch. Eventually, it tends to pass if we are lucky and the node is fast enough.
Double the wait time from 5 to 10 minutes.

[th/wait-worker-rename] clusterDeployer: increase wait-time for worker node

---

dependencies.sh

root cause
```
(ocp-venv) [root@prov]# which $PYTHON_CMD
/root/dpu-operator/cluster-deployment-automation/ocp-venv/bin/python
(ocp-venv) [root@prov]# sudo -E which $PYTHON_CMD
/bin/python
```

Fixing python build break

---

auth.py

The directory doesn't exist in various cases, which causes a crash. Create the directory first.

[th/auth-ensure-dir] auth: ensure "/run/user/0/containers" exists

---

clustersConfig.py
dpuVendor.py
ipu.py

Revert Intel IPU SDK1.8 specific workarounds and enable SDK2.0 changes

Revert Intel IPU SDK1.8 specific workarounds and enable SDK2.0 changes

---

ipu.py

This workaround is not required with the latest IPU SDK update.

Remove workaround added in the past to free up some space on IMC

---

arguments.py
cda.py
cdaConfig.py
clusterDeployer.py
clusterSnapshotter.py
state_file.py

deploy --resume
state subcommand  
--reset 
Currently only one state file at a time. If a new config is deployed the state gets cleared (even if the cluster is still deployed).
If a step is interrupted halfway through, resuming will restart the whole step. 
Without --resume, clusters will always be redeployed as they are currently.

Initial state file implementation. 

---

assistedInstallerService.py

The earlier images seem broken. When installing SNO cluster with the example config from the README, it was hanging.
Update the assisted installer images, which makes it work again.

[th/assisted-installer-update-images] assisted-installer: update version of installer images

---

ipu.py

As of MEV-TS 2.0, BootOnce behaves properly.
There is no need to disable the system boot option anymore.
Handles IIC-613

Redfish BootOnce actually works now

---

common.py

mypy 1.16 now better detects the type, which leads to a [redundant-cast] warning:
```
common.py:294: error: Redundant cast to "list[Any]"  [redundant-cast]
```
Older versions couldn't figure that out, so the type was `Any` and we needed the cast to avoid "[no-return-any]".
Add another workaround for the issue, which should work with older and newer mypy.

[th/fix-mypy-parse-json-list] common: avoid [redundant-cast] warning in _parse_json_list()

---

isoDeployer.py

Fixes: 969a134a5b4e ('unwrap from general structure')

isoDeployer: drop unused import for ThreadPoolExecutor

---

clusterDeployer.py
imageRegistry.py

Fixes:
- Wait cluster waits over an 1 hour because of Kube-api operator and OpenShift controller operator doesn't get ready at the correct time. We don't need that check since for the image registry we check for the relevant operators readiness anyway.
- Bumps retries for waiting on default route for register to be available
- Explicitly waits after applying patches to fully apply.
- Http check for the library to make sure the image registry is up at the service/application level.

fix(image-registry): Need readiness checks

---

dependencies.sh
k8sClient.py

The k8sClient was ensuring that OCP client is installed, however, it wasn't ever updated once installed. Let's try to pull latest stable version during dependencies installation.

Install OCP client in dependencies.

---

assistedInstaller.py

When using dirname it actually tries to make "/home" since the path provided is already to the directory instead of the iso file. To achieve the expected behavior, we actually have to use the path as is.

fix(assistedInstaller): Correct makedirs target

---

host.py
ipu.py

Replace pre_init_app.sh with a version that allows new modules to be added into /work/scripts/pre_init_app.d/ for as close to a systemd ability as we can get on the current architecture.
locate the most recent chrony package on the rockylinux server, check in both /pub and /vault as they rename the folders for some reason. 
add /work/script/pre_init_app.d/chrony.sh which installs chrony (needed at every imc reboot)
start chrony during the setup phase
if a rpm file is not found, as a failsafe set the time on the imc to the time of the provisioning host. This is good enough to get the current iso installed, though redfish may have issues connecting in the future. But at least the CI test will succeed regardless
print the time reported from the imc for the sake of the logs.
Copying the rpm …

Install chrony on IMC

---

assistedInstallerService.py
clusterDeployer.py
clusterNode.py
common.py

Fixes RHCOS issues by switching to newer images
There seems to be a race condition in ensure_reboot
since libvirt already has the setting to auto-restart
VMs on reboot (--events on_reboot=restart).
The original code would:
1. Wait for VM to stop after reboot
2. Try to manually start it with `virsh start`
3. Fail with "Domain is already active" if the VM 
had already auto-restarted
Now we gracefully handle this race condition by:
- Detecting if the VM auto-restarted during our wait
- Only attempting manual start if VM is still stopped
- Treating "Domain is already active" as success
- Continuing normally in either case
This eliminates spurious CI failures when the auto-restart
happens faster than our reboot detection logic.
- Capture assisted-installer container logs from all related …

Fix master node failure and add log capture + Bump AI

---

bmc.py

We have
class BMC:
def __init__(self, full_url: str, ...):
self.url = full_url
but call
BMC(ip_or_hostname, user, password)
This means, some (all?) callers set the "full_url" and "self.url" to an IP address or hostname.
Later we build a complete URL, but (usually?) there is no URL scheme. This leads to
requests.exceptions.MissingSchema: Invalid URL '10.26.16.95/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Manager.Reset': No scheme supplied. Perhaps you meant https://10.26.16.95/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Manager.Reset?
See-also: https://jenkins-csb-nst-net-hw-ci.dno.corp.redhat.com/job/99_E2E_Marvell_DPU_Deploy/581/console

[th/bmc-base-url] bmc: ensure scheme in URL for redfish Reset

---

ipu.py

Redfish team initially gave guidance to use the word "custom", but due to some apparent corner cases where "custom" showed up in redfish logs for hard failures, we will now go with "iscsi" which is the initial condition of this parameter after a stock install.
Validated by CI#1773 for PR507 in dpu-operator

adjust redfish workaround

---

ipu.py

With this change, redfish should start immediately, regardless of dhcp status, and listen on all addresses.
This should solve the issue experienced when dhcp acquisition is slow.

Do not bind redfish to particular address

---

ipu.py

IPUBMC.ensure_started() called
self._create_imc_rsh().wait_ping()
But _create_imc_rsh() tries to SSH into the host, with a timeout of one hour. On failure (and after one hour), it fails with an exception that was not expected by the caller and lead to a crash.
Instead, use a timeout of "only" 5 minutes, and hide the exception. There is no need for Host.wait_ping(), because Host.ssh_connect() already does a ping internally.
This works around the most glaring problems with this. On Marvell cluster, the "is_ipu()" check would wait to start the machine, which then fails to be accessible via SSH. More patches will follow to solve this better.

ipu: don't crash during IPUBMC.ensure_started()
