- arguments.py
- clusterDeployer.py
Signed-off-by: William Zhao <wizhao@redhat.com>
> Add list argument to skip certain steps in deployment

- clustersConfig.py
- coreosBuilder.py
- host.py
Signed-off-by: William Zhao <wizhao@redhat.com>
> Add documentation to scripts

- extraConfigSriov.py
Signed-off-by: William Zhao <wizhao@redhat.com>
> Fix trailing new line character in interface name

- clusterConfigSchema.yml
- clusterDeployer.py
- clustersConfig.py
- common.py
- extraConfigBFB.py
- host.py
add dom entries and default automatic value for both items
additionally add a wrapper shell script do automate the setup steps
> allow configuration of enternal and external interfaces

- README.md
- clusterDeployer.py
- dependencies.sh
Also updated the README.md to point to installing dependencies using dependencies.sh.
Improve the verbosity of failing to install VMs
> Add mandatory packages that need to be installed in dependencies.sh

- extraConfigSriov.py
Some servers seem to not be able to populate the iface_default_hint file.
> Use ovs-vsctl as a fall back if we can't find the PF Name using hints

- clustersConfig.py
Make sure to append the last cluster in the spreadsheet
> Add last cluster

- common_patches.py
- extraConfigDpuInfra.py
- extraConfigDpuTenant.py
- manifests/common/monitor-patch-cm.yaml
- manifests/tenant/nmo-subscription.yaml
1. Create node maintenance operator on tenant
2. Common patches to disable running dns, ingress and monitoring parts on workers
> Adding patches for infra and tenant clusters:

- extraConfigDpuTenant.py
This commit fixes a number of small bugs in the DpuTenant configuration which currently require manual updating post install.
- Update MGMT_IFNAME from eth1 to c1pf0vf0
- env-overrides should work with new interface i.e. ens7f0np0
- ovnkubeconfig patch currently fails every time due to syntax error ("Error from server: error decoding patch: ...")
> Fix DpuTenant Configs

- assistedInstallerService.py
Currently unable to deploy 4.14.
> use 4.14 pullspec

- assistedInstallerService.py
Assisted service/image-service/installer will need to be updated in lockstep with the container images when using the same versions as saas.
This version can be found here:
https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/assisted-installer/cicd/target/production/assisted-service.yaml
> Update assisted service image

- arguments.py
- assistedInstallerService.py
- main.py
Option to remove everything we installed - included stop ai.
Optional, disabled by default
> Optionally stop assisted installer when tearing down

- extraConfigDpuInfra.py
- extraConfigSriov.py
Deployments have been failing since there seems to be a delay before the PF is added to br-ex.
Add a more robust check for the PF.
> Add retries when getting PF name

- clusterDeployer.py
Fixes potential issues with bridges and dhcp
> Fix bridge and dhcp

- arguments.py
- assistedInstaller.py
- assistedInstallerService.py
- clusterDeployer.py
- clustersConfig.py
- coreosBuilder.py
- host.py
nit to make pylint happier
some logging change
> Nit and logging

- clusterConfigSchema.yml
- clusterDeployer.py
- clusterSnapshotter.py
- clustersConfig.py
- host.py
A few commits mainly adding methods which will be used in next PR
caching host class as we do not recreate remotehost each time, which would require passing parameters such as password, ...
> Prepare for remote vms

- clusterDeployer.py
- clustersConfig.py
Add additional config to specify proxy in format:
http://username:password@proxy_server_address:port
> clustersConfig: Allow users to override http_proxy

- extraConfigDpuTenant.py
Should be worker instead of workers.
> Fix typo in BF mapping for worker

- README.md
> update docs to 3.11

- arguments.py
- cda.py
- clustersConfig.py
- common.py
It's useful when batching deployments.
> Add cmdline support to skip/select a subset of the worker range.

- clusterDeployer.py
- common.py
- microshift.py
- added the ability to detect ssh keys beyond `id_rsa.pub`
> add wildcard pub key to `generate_kickstart`

- .gitignore
- README.md
- clusterConfigSchema.yml
- clusterDeployer.py
- clustersConfig.py
- extraConfigBFB.py
- extraConfigCX.py
- host.py
- microshift.py
- microshift.yml
- remove references to bmc_from_host_name function
- use `bmc = BMC.from_ip` instead
- add more files to .gitignore
> Remove bmc plus one

- .flake8
- arguments.py
- clusterDeployer.py
- common.py
- extraConfigCX.py
- extraConfigCustomOvn.py
- extraConfigDpuTenant.py
- extraConfigSriov.py
- host.py
- microshift.py
Even if mypy is already used, flake8 seems useful too.
Add a `.flake8` file and fix warnings.
To run it, just run `flake8` in the root directory.
Later, maybe this should be hooked up in .github actions.
> [th/flake8] add flake8 configuration file and fix warnings

- clusterDeployer.py
- logger.py
Add a `logger.fatal()` helper as convenience wrapper around `logger.error() + sys.exit()`.
Use it in `clusterDeployer.py`.
Also, adjust the level of some log messages before failing. Should log ERROR messages instead of INFO.
> logger: add logger.fatal() helper and use it in clusterDeployer.py

- k8sClient.py
Since commit b2db1d4f2114 ('Fixed dependencies.sh to install ocp client.'), "dependencies.sh" downloads "openshift-client-linux.tar.gz" and unpacks it in /usr/local/bin. We thus should always have `oc` and `kubectl` in $PATH.
Drop ensure_oc_binary() from "k8sClient.py", which also downloaded the oc binary and placed it in the build directory. It seems redundant.
In general, the user of the script should ensure that a suitable oc tool is in $PATH. The easiest way to get that is by running "dependencies.sh".
---
Follow up for https://github.com/bn222/cluster-deployment-automation/pull/122#issuecomment-2009187083
> [th/no-ensure-oc-binary] k8sClient: drop oc_bin binary in build directory

- assistedInstallerService.py
Resolves an issue I had where cda was hanging on "stopping assisted installer".
```
2024-03-29 16:31:44 INFO: assisted-installer already exists but status is Error
2024-03-29 16:31:45 INFO: Stopping assisted-installer
```
> Combine podman stop, rm into one step

- clusterNode.py
If a node can't boot up for whatever reason (e.g., for VM nodes the physical host was missing the right packages) CDA was infinitely looping waiting for the host to come up.
Instead, detect that the boot-time future has completed and report errors in the health_check() stage.
With this patch applied I now get (in my invalid deployment):
```
2024-04-03 08:24:52 ERROR: Failed to provision node dceara-bm-worker-1: ERROR    Host does not support any virtualization options
The program exited via sys.exit(). Exit status: -1
```
> clusterNode: Properly detect nodes that failed to boot up.

- extraConfigDpuInfra.py
- extraConfigDpuTenant.py
- extraConfigSriov.py
- extraConfigDpuInfra: extract common code for extraConfigDpuInfra(,_NewApi}
- extraConfigDpuInfra: construct JSON from a Python structure instead of plain string
Follow up to https://github.com/bn222/cluster-deployment-automation/pull/128#discussion_r1531100049
> [th/extraConfigDpuInfra-cleanup] minor cleanup in `extraConfigDpuInfra.py`

- arguments.py
- cda.py
- clusterConfigSchema.yml
- clusterDeployer.py
- clustersConfig.py
This allows setting up DHCP and AI on a host and then deploy multiple clusters that get IPs and use AI from that single host.
> Allow multiple clusters with single dhcp.

- .github/workflows/test.yml
> [th/ci-pytest] github: run pytest in github actions

- extraConfigImageRegistry.py
Otherwise there's a risk that not all components are ready to use.
> extraConfigImageRegistry: Wait for the change to completely rollout.

- assistedInstallerService.py
The `pod-persistent.yml` contains a few `persistentVolumeClaim` objects that create a couple of persistent volumes `ai-service-data` and `ai-db-data`.  These volumes are not part of the pod per se and not belong directly to any of the created containers.  So, the basic `podman pod rm -f` doesn't remove them.
Use `podman kube down --force` to properly destroy all the resources defined in the configuration yml.
Unfortunately, this command is not available in older podman, so falling back to the old method in this case.  The command should work starting with podman 4.3.
Some older versions of podman support `kube play --down` instead, but also supporting this version of a fallback doesn't seem to make a lot of sense as the number of versions that support it, but doesn't support `kube down` …
> assistedInstallerService: Properly clean up persistent volume claims.

- clusterNode.py
This issue was caught when the subtask ran into an exception, but the error message was not of the subtask getting into an exception. This is not helpful in debugging.
> Fix Future Exception Handling

- nfs.py
It happens frequently, that two threads at the same time try to run `NFS.host_file()`.
Consequently the `systemctl restart nfs-server.service` fails. Since commit fbf00fa192c6 this is fatal. But even before, this can leave NFS export broken, which causes failures later on.
- add a lock around `NFS.host_file()` so that two threads don't interfere (another process of course still can interfere).
- retry a few times to restart the service before giving up.
> [th/nfs-lock] add lock around NFS.host_file() and retry restarting nfs-server.service

- clustersConfig.py
The first time we run CDA on a freshly installed cluster, the default network may not exist yet.
i.e.
error: failed to connect to the hypervisor
error: Operation not supported: Cannot use direct socket mode if no URI is set. For more information see https://libvirt.org/kbase/failed_connection_after_install .html
This will cause the following to fail:
"""
xml_str = hostconn.run("virsh net-dumpxml default").out tree = et.fromstring(xml_str)
"""
> Handle case when virsh network does not yet exist

- extraConfigDpu.py
- Removed the TODO/FIXME and setting sriov_numvfs
> The sriov_numvfs is now configured by DPU Operator

- clusterDeployer.py
- clusterHost.py
- host.py
- logger.py
- virtualBridge.py
Add some small improvements that should help with some of the logging messages.
> Improve logging

- README.md
- Added information about pull_secret and where to get it.
- Added note to remember to replace placeholders in config example.
- Replaced error-causing depreciated ingress_ip option with ingress_vip in config example.
- Added note about default behavior concerning kubeconfig, and its naming convention.
> Update README with Up-to-date info (New Environment)

- clusterInfo.py
- Changed read_sheet to return a list of dictionaries instead of list of lists
- Changed load_all_cluster_info to access collumns by collumn names in the row dicts instead of by hardcoded index
> Upgrade sheet reading to be stable against sheet changes

- test_common.py
When running as root, we have CAP_DAC_OVERRIDE and can read the file even if we don't have unix permissions. Work around that.
> [th/test-fix-atomic-write] common/tests: fix unit test test_atomic_write()

- clusterInfo.py
Changed the column name to align with the hardware sheet and prevent CDA issues caused by mismatched column names.
> Update column name from "IPMI" to "BMC/IMC hostname"

- extraConfigBFB.py
Resolved an issue where the sriov_ovs_hwol postconfig step caused workers to enter a boot loop.
The problem stemmed from workers not switching from DPU to NIC mode, which required a cold boot to fix.
This commit ensures the CDA triggers a cold boot, allowing workers to successfully transition to NIC mode.
> Ensure Cold Boot for Successful DPU to NIC Mode Switch

- clustersConfig.py
- common.py
- extraConfigDpu.py
Add pull number to cluster config schema allowing CDA to checkout a branch associated with a specific pull number for testing
> Add ability to checkout specific pull number for dpu operator

- clusterInfo.py
- clustersConfig.py
Store the BMC/MAC information in the spreadsheet.
> Add reading IMC hostname and MAC Address from spreadsheet

- ipu.py
f-string was within the quotes
> ipu.py: Fix typo

- host.py
- ipu.py
See-also: https://issues.redhat.com/browse/IIC-379?focusedId=25751021&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25751021
https://issues.redhat.com/browse/IIC-384
> [th/ipu-virtual-media-inserted] ipu: poll Redfish API while waiting for ISO to be inserted

- assistedInstaller.py
mypy also warns:
```
assistedInstaller.py:136: error: Argument 1 to "append" of "list" has incompatible type "dict[Any, Any]"; expected "ClusterInfo"  [arg-type]
```
> [th/ai-list-clusters] assistedInstaller: fix list_clusters() implementation

- ipu.py
Redfish might not be running, so we need the fallback check for the version via SSH.
https://github.com/bn222/cluster-deployment-automation/commit/c80a04e0a839fa52fd664a9062dc41f14a53a282#r148561539
Fixes: c80a04e0a839 ('ipu: fetch BMC "FirmwareVersion" via redfish HTTP API')
> [th/version-via-ssh] ipu: also check BMC "FirmwareVersion" via SSH

- ipu.py
Fixes: 1d5a9ea3eba0 ('Remove support for old IPU versions')
> [th/ipu-fix-logging] ipu: fix logging and avoid flake8 warning

- dpuVendor.py
- extraConfigDpu.py
- ipu.py
- k8sClient.py
- manifests/dpu/dpu_p4_ds.yaml.j2
- manifests/dpu/dpu_vsp_ds.yaml.j2
Moving the P4 daemonset has broken the p4 pod, this PR adds the necessary changes to fix this.
In addition, the cold boot behavior is not working in an automated fashion. Add some changes and additional checks to make sure this is working properly.
> Fix CI issues

- clusterHost.py
- clusterNode.py
- ipu.py
- clusterNode: fix post_boot() abstraction
- clusterNode: factor out common implementation for has_booted() method
> [th/cluster-node-methods] cleanup NodeCluster methods post_boot()/has_booted()

- assistedInstaller.py
- clusterDeployer.py
- clusterHost.py
- libvirt.py
- virtualBridge.py
Slightly simplify the deployment process by moving/creating some additional helper functions.
> deployment: Slightly simplify the deployment process

- ipu.py
We should no longer have to run this script manually
> Remove workaround for IIC-427

- clusterInfo.py
When specifying both "--host" and "--cluster" options, it seems to make the most sense that both selectors must match. Fix that.
Now `python clusterInfo.py host -H hostname -c clustername` works as one would(?) expect. It returns a result only if both the "-H" and "-c" option matches, and if only a single matching result is found. Otherwise an error is raised:
```
No cluster info for host 'hostname' and for cluster  matching 'clustername' found. Select a host with "--host" or "--cluster" option?
```
This implementation no longer uses a dictionary lookup, it always iterates over all entries. But since there is only a handful of entries, the performance impact is irrelevant (especially compared to the time we spend to fetch a document from the web).
> [th/cluster-info-fix-match] clusterInfo: fix load_cluster_info() to require full match

- dpuVendor.py
- extraConfigDpu.py
- manifests/dpu/p4_service.yaml
* Start P4 from the ds yaml
* Making p4rt gRPC service as a local cluster only and removing NodePort
> Enabling P4 as a pod

- clustersConfig.py
- extraConfigCustomOvn.py
- manifests/ovn/Dockerfile
Allow user to specofy which repository and branch/commit should be used to build the upgrade rpm from.
@dceara
> ovn: Allow user to specify custom OVN repo and ref

- dependencies.sh
address a minor issue with dependencies. Thanks to Balazs for assisting with the fix :-)
> balazs fixed the argcomplete issue

- dpuVendor.py
> Fix p4.tar.gz RH specific server issue

- dpuVendor.py
This reverts commit 6789b8378c37570a8598dd2f8890369edab5edf7.
> Revert "Revert p4 changes"

- clusterDeployer.py
- clusterHost.py
- clustersConfig.py
- host.py
- virtualBridge.py
In order to allow BM master we need to make sure that DHCP is available and the bridge is setup correctly. Also make sure we copy the image into proper directory as it there was implicit contract that it will be copied for VMs.
> Some smaller fixes to allow BM masters

- cda.py
- isoDeployer.py
- state_file.py
Add state file changes to isodeployer
> IsoDeployer state

- ipu.py
I had an implementation working with BeautifulSoup, but your mypy kept complaining about the href=link.get() call, so I went this direction.
> chrony download fix
